version: '3'

tasks:
  migrate:
    desc: Apply migrations
    cmds:
      - python manage.py makemigrations
      - python manage.py migrate

  run:
    desc: Run server
    cmds:
      - python manage.py runserver