# Generated by Django 6.0.3 on 2026-06-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_items', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer_name', models.CharField(blank=True, max_length=150, verbose_name='Имя получателя')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='Электронная почта')),
                ('customer_phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон')),
                ('delivery_address', models.TextField(blank=True, verbose_name='Адрес доставки')),
                ('status', models.CharField(choices=[('NEW', 'Новый'), ('PROCESSING', 'В обработке'), ('DELIVERED', 'Доставлен'), ('CANCELLED', 'Отменён')], default='NEW', max_length=16, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('-created_at',),
            },
        ),
    ]
